[package]
name = "exercise1_dependencies_and_the_window"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
winit = "0.30.12"
env_logger = "0.11.8"
log = "0.4"
wgpu = "26.0.1"
pollster = "0.4.0"