[package]
name = "ex4_buffers_and_indices_challenge"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.99"
winit = "0.30"
env_logger = "0.11"
log = "0.4"
wgpu = "26"
pollster = "0.4"
bytemuck = "1.23"